export const Users = [
    {
      id:1,
      profilePicture: "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "https://d2qp0siotla746.cloudfront.net/img/use-cases/profile-picture/template_3.jpg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "https://th.bing.com/th/id/OIP.L8bs33mJBAUBA01wBfJnjQHaHa?pid=ImgDet&rs=1",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "https://th.bing.com/th/id/OIP.goGk6M0435GIC2xz7vZEMQHaLI?pid=ImgDet&rs=1",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "https://th.bing.com/th/id/OIP._6kSqsTmX5o4yeSjGnw48AHaLH?pid=ImgDet&rs=1",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "https://images.unsplash.com/photo-1529665253569-6d01c0eaf7b6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "https://th.bing.com/th/id/OIP.OF49gkEuC_ct2_xLgAguGgHaLH?pid=ImgDet&rs=1",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "https://cdn6.f-cdn.com/files/download/38546484/28140e.jpg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://th.bing.com/th/id/OIP.lbNwtS5QHxECLgBVO2ZLzAHaEK?pid=ImgDet&rs=1",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://th.bing.com/th/id/OIP.qlKFL_JPioo8SRcpEXgTVQHaE8?pid=ImgDet&rs=1",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://www.allprodad.com/wp-content/uploads/2021/03/05-12-21-happy-people.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://th.bing.com/th/id/OIP.2lSzD9S7DK502f3YAbkpKwHaFU?pid=ImgDet&rs=1",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://www.wsha.org/wp-content/uploads/banner-diverse-group-of-people-2.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://th.bing.com/th/id/R.fe5eb9e42a3c8918cd9d6091dc6d97ed?rik=cEtDX7y0UNBTVg&riu=http%3a%2f%2fwww.smcyinternationalfamily.org%2fwp-content%2fuploads%2f2018%2f01%2fHappy-People1-1.jpg&ehk=G4ZqJOkCpX9CPyfMhS0tbTXVLvNkRn2%2bzGGigT5jgbY%3d&risl=&pid=ImgRaw&r=0",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "https://th.bing.com/th/id/OIP.XDK28gahENTFk8mVlyuY8QHaE7?pid=ImgDet&rs=1",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://th.bing.com/th/id/OIP.9kvuvj_y9GWIs_XqzUUTTgHaEc?pid=ImgDet&rs=1",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://assets.ey.com/content/dam/ey-sites/ey-com/en_gl/topics/global-review/2019/ey-staff-at-event.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://th.bing.com/th/id/R.43df43ebcc0f19366e86f220d8f7b8af?rik=KI5BYnaPCx%2blug&riu=http%3a%2f%2fwww.mentorworks.ca%2fwp-content%2fuploads%2f2013%2f06%2fbigstock-Business-People-Isolated-6327666.jpg&ehk=0qwgp9%2b0NpWdceml8CDcAz0xesTHztDPepTWUiXCO8U%3d&risl=&pid=ImgRaw&r=0",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];